name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Display version information
      run: node --version && npm --version
    - name: Install NPM packages
      run: cd "$GITHUB_WORKSPACE"/export-server && npm install
    - name: Tests
      run: cd "$GITHUB_WORKSPACE"/export-server && ./test.sh
